---
- hosts: CentOS
  roles:
    - centos-elastic
    - centos-grafana
    - centos-lamp

- hosts: Server1
  gather_facts: True
  roles:
    - ubuntu-elastic
    - ubuntu-nagios
    - ubuntu-nagios2
    - ubuntu-nagios3
    - ubuntu-grafana
    - ubuntu-lamp
  become: true
